import { describe, expect, it } from "vitest";
import { buildClubAchievements, type AchievementMatch, type AchievementSession } from "./clubAchievements";
const members=["me","a","b","c"];
function match(index:number,win=true,partner="a",delta?:number):AchievementMatch { return {id:`m${index}`,date:new Date(Date.UTC(2026,0,5,0,index)).toISOString(),team1:["me",partner],team2:members.filter(id=>id!=="me"&&id!==partner),winner:win?1:2,score1:win?21:19,score2:win?19:21,ratingDelta:delta===undefined?{}:{me:delta}}; }
function session(matches:AchievementMatch[],index=0,extra:Partial<AchievementSession>={}):AchievementSession {return {id:`s${index}`,code:`s${index}`,name:`Session ${index}`,date:new Date(Date.UTC(2026,0,5+index*7,2)).toISOString(),hostId:"me",eligibleIds:members,guests:[],matches,...extra};}
function badge(id:string,sessions:AchievementSession[],current=members) { return buildClubAchievements("me",current,sessions,new Date("2026-01-05T12:00:00Z")).find(a=>a.id===id)!; }
describe("club achievements",()=>{
 it("starts locked without games, including an empty denominator",()=>{for(const a of buildClubAchievements("me",["me"],[]))expect(a.earnedTier).toBe(0);});
 it("earns first serve only for participating members",()=>{expect(badge("first-serve",[session([match(1)])]).earnedTier).toBe(1);expect(badge("first-serve",[session([match(1)],0,{guests:["me"]})]).earnedTier).toBe(0);});
 it("small clubs can reach every coverage tier",()=>{const b=badge("mix-it-up",[session([match(1,true,"a"),match(2,true,"b"),match(3,true,"c")])]);expect(b.earnedTier).toBe(3);expect(b.progressLabel).toBe("3 of 3 clubmates · 100%");});
 it("same partner in different sessions counts once",()=>{const b=badge("mix-it-up",[session([match(1)]),session([match(2)],1)]);expect(b.progress).toBeCloseTo(100/3);expect(b.earnedTier).toBe(1);});
 it("never loses an earned coverage tier when eligible members join",()=>{const old=session([match(1,true,"a"),match(2,true,"b"),match(3,true,"c")]);const later=session([{...match(4),team2:["d","c"]}],1,{eligibleIds:[...members,"d"]});const b=badge("mix-it-up",[old,later],[...members,"d"]);expect(b.earnedTier).toBe(3);expect(b.progress).toBe(75);});
 it("preserves coverage awards when a former partner leaves",()=>{const b=badge("mix-it-up",[session([match(1,true,"a"),match(2,true,"b"),match(3,true,"c")])],["me","a","b"]);expect(b.earnedTier).toBe(3);});
 it("recomputes invalid awards after corrected or removed results",()=>{const complete=session([match(1,true,"a"),match(2,true,"b"),match(3,true,"c")]);expect(badge("mix-it-up",[complete]).earnedTier).toBe(3);expect(badge("mix-it-up",[{...complete,matches:complete.matches.slice(0,1)}]).earnedTier).toBe(1);});
 it("excludes temporary guest partners from coverage but counts match wins",()=>{const games=Array.from({length:10},(_,i)=>match(i));const s=session(games,0,{guests:["a"]});expect(badge("mix-it-up",[s]).progress).toBe(0);expect(badge("on-the-board",[s]).earnedTier).toBe(1);});
 it("requires at least four games for a clean sweep",()=>{expect(badge("clean-sweep",[session([match(1),match(2),match(3)])]).earnedTier).toBe(0);expect(badge("clean-sweep",[session([match(1),match(2),match(3),match(4)])]).earnedTier).toBe(1);});
 it("counts each comeback once and resets losses across sessions",()=>{expect(badge("back-in-business",[session([match(1,false),match(2,false),match(3,false),match(4),match(5)])]).progress).toBe(1);expect(badge("back-in-business",[session([match(1,false),match(2,false)]),session([match(3)],1)]).progress).toBe(0);});
 it("counts wins with each partner separately",()=>{expect(badge("good-together",[session([match(1),match(2),match(3,true,"b"),match(4,true,"b")])]).progress).toBe(2);});
 it("ignores unrated games and establishes rating baseline after ten rated games",()=>{const first=Array.from({length:10},(_,i)=>match(i,true,"a",100));expect(badge("raising-bar",[session(first)]).progress).toBe(0);expect(badge("raising-bar",[session([...first,match(11,true,"a",50)])]).earnedTier).toBe(1);expect(badge("raising-bar",[session([...first,match(11)])]).progress).toBe(0);});
 it("preserves earned peak after match losses",()=>{const games=Array.from({length:10},(_,i)=>match(i,true,"a",0));expect(badge("raising-bar",[session([...games,match(11,true,"a",50),match(12,false,"a",-30)])]).earnedTier).toBe(1);});
 it("counts close wins only at a one or two point margin",()=>{expect(badge("down-to-wire",[session([match(1),match(2),{...match(3),score2:18}])]).progress).toBe(2);});
 it("credits only recorded creator and qualified hosting sessions",()=>{const games=Array.from({length:4},(_,i)=>match(i));expect(badge("making-it-happen",[session(games)]).earnedTier).toBe(1);expect(badge("making-it-happen",[session(games,0,{hostId:null})]).earnedTier).toBe(0);});
 it("keeps weekly tier earned after inactivity without faking current streak",()=>{const ss=[0,1,2].map(i=>session([match(i)],i));const a=buildClubAchievements("me",members,ss,new Date("2026-04-01")).find(a=>a.id==="rhythm")!;expect(a.earnedTier).toBe(1);expect(a.progress).toBe(0);});
});
