ALTER TABLE "User" ADD COLUMN "gender" TEXT NOT NULL DEFAULT 'UNSPECIFIED';
ALTER TABLE "User" ADD COLUMN "partnerPreference" TEXT NOT NULL DEFAULT 'OPEN';

ALTER TABLE "Session" ADD COLUMN "mode" TEXT NOT NULL DEFAULT 'MEXICANO';

ALTER TABLE "SessionPlayer" ADD COLUMN "gender" TEXT NOT NULL DEFAULT 'UNSPECIFIED';
ALTER TABLE "SessionPlayer" ADD COLUMN "partnerPreference" TEXT NOT NULL DEFAULT 'OPEN';
