import { useEffect, useState } from 'react';
import { House, UsersThree, UserCircle, ChartBar, CaretRight, ArrowLeft, DotsThree, MagnifyingGlass, Plus, PencilSimple, LinkSimple, Check, Clock, Trophy, GearSix, Pause, Play, X, ArrowUp, CalendarBlank, SignOut, Minus } from '@phosphor-icons/react';
import { MobileScroll, BottomSheet, KeyboardInput, useKeyboard, useKeyboardInsets, useScreenPortal } from './mobile';
import '@fontsource/nunito-sans/400.css';
import '@fontsource/nunito-sans/600.css';
import '@fontsource/nunito-sans/700.css';
import '@fontsource/nunito-sans/800.css';
import '@fontsource/nunito-sans/900.css';

type Page='sessions'|'home'|'clubs'|'club'|'profile'|'admin'|'session'|'recap'|'setup';
type Player={name:string;rating:number;role:string;paused?:boolean};
const initial:Player[]=[{name:'Aiman',rating:1059,role:'Owner'},{name:'Siti',rating:1028,role:'Member'},{name:'Farah',rating:1010,role:'Member'},{name:'Amir',rating:1000,role:'No account'},{name:'Haziq',rating:990,role:'Occasional'},...['Danish','Aina','Mira','Irfan','Nadia','Rafi','Zul'].map(name=>({name,rating:1000,role:'Member'}))];
type ClubConfig={id:string;name:string;owner:boolean;rating:number;rank:number;recent:string;wins:number;games:number};
const samples:ClubConfig[]=[{id:'anti',name:'Anti-Selek',owner:true,rating:1059,rank:3,recent:'Evening Rally',wins:4,games:6},{id:'weekend',name:'Weekend Collective',owner:false,rating:1184,rank:7,recent:'Sunday Social',wins:3,games:5}];
function readLast(){try{return localStorage.getItem('pc-selected-club')}catch{return null}}
export default function Prototype(){
 const [clubs,setClubs]=useState(samples);const [selected,setSelected]=useState<string|null>(()=>{const id=readLast();return samples.some(c=>c.id===id)?id:null});
 const [form,setForm]=useState(''),[value,setValue]=useState(''),[notice,setNotice]=useState('');const keyboard=useKeyboard();
 function select(id:string){keyboard.hide();setSelected(id);try{localStorage.setItem('pc-selected-club',id)}catch{}}
 return <>{clubs.map(c=><div key={c.id} style={{display:selected===c.id?'contents':'none'}}><ClubPrototype config={c} active={selected===c.id} onSwitch={()=>{keyboard.hide();setSelected(null)}}/></div>)}{selected===null&&<div className="pc-app"><header className="pc-header"><span className="brand">Anti-Selek<span>.</span></span><button className="avatar small tone0" aria-label="Account" onClick={()=>setNotice('Signed in as Aiman · sample account')}>A</button></header><MobileScroll className="pc-scroll"><main className="pc-content chooser"><div className="chooser-intro"><span className="eyebrow">YOUR CLUBS</span><h1>Where are we<br/>playing?</h1><p>Choose your club to get started.</p></div>{clubs.map((c,i)=><button className="club-choice" onClick={()=>select(c.id)} key={c.id}><span className={'club-mark tone'+i}><UsersThree size={28} weight="duotone"/></span><span><strong>{c.name}</strong><small>{c.owner?'Owner':'Member'}{c.id==='anti'?' · 12 players':c.id==='weekend'?' · 4 players':' · New club'}</small>{c.id==='anti'&&<em>Session in progress</em>}</span><CaretRight size={20}/></button>)}<div className="chooser-actions"><button className="secondary" onClick={()=>{setForm('create');setValue('')}}><Plus size={19}/>Create club</button><button className="text-button" onClick={()=>{setForm('join');setValue('')}}><LinkSimple size={19}/>Join a club</button></div>{form&&<div className="card"><label className="field-label">{form==='create'?'Club name':'Invite link'}<KeyboardInput value={value} onChange={e=>setValue(e.target.value)} placeholder={form==='create'?'Your club name':'Paste an invite link'}/></label><button className="primary" disabled={!value.trim()} onClick={()=>{keyboard.hide();if(form==='create'){const c={id:'club-'+Date.now(),name:value.trim(),owner:true,rating:1000,rank:0,recent:'No sessions yet',wins:0,games:0};setClubs(x=>[...x,c]);select(c.id)}else setNotice('Sample join request sent');setForm('')}}>{form==='create'?'Create club':'Request to join'}</button><button className="text-button" onClick={()=>{keyboard.hide();setForm('')}}>Cancel</button></div>}{notice&&<p role="status" className="muted">{notice}</p>}</main></MobileScroll></div>}</>
}
function ClubPrototype({config,onSwitch,active}:{config:ClubConfig;onSwitch:()=>void;active:boolean}){
 const [page,setPage]=useState<Page>('club'),[tab,setTab]=useState('Courts'),[adminTab,setAdminTab]=useState('Players');
 const [players,setPlayers]=useState(()=>config.id==='anti'?initial:[{name:'Aiman',rating:config.rating,role:config.owner?'Owner':'Member'},...(config.id==='weekend'?[{name:'Leena',rating:1240,role:'Owner'},{name:'Kai',rating:1205,role:'Member'},{name:'Sara',rating:1160,role:'Member'}]:[])]),[query,setQuery]=useState(''),[sheet,setSheet]=useState(''),[edit,setEdit]=useState<number|null>(null);
 const [name,setName]=useState(''),[rating,setRating]=useState('1000'),[role,setRole]=useState('Member'),[toast,setToast]=useState('');
 const [scores,setScores]=useState([['18','16'],['0','0']]),[saved,setSaved]=useState([false,false]),[court,setCourt]=useState(0),[ended,setEnded]=useState(config.id!=='anti'),[nextStarted,setNextStarted]=useState(false);
 const [requests,setRequests]=useState(['Nadia wants to connect her account','Rafi wants to join the club']),[clubName,setClubName]=useState(config.name),[sessionName,setSessionName]=useState(config.recent),[draft,setDraft]=useState(''),[extraClubs,setExtraClubs]=useState<string[]>([]),[openClub,setOpenClub]=useState(true);
 const {screenRef}=useScreenPortal(); function keepFrameStill(){requestAnimationFrame(()=>screenRef.current?.scrollTo(0,0))} const keyboard=useKeyboard();const {bottomInset,keyboardHeight}=useKeyboardInsets();
 useEffect(()=>{const screen=screenRef.current; const reset=()=>{if(screen?.scrollTop)screen.scrollTop=0}; screen?.addEventListener('scroll',reset);return()=>screen?.removeEventListener('scroll',reset)},[screenRef]);
 useEffect(()=>{if(active)setPage('club')},[active]);
 useEffect(()=>{document.title='Anti-Selek · Play Collective';},[]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2600);return()=>clearTimeout(t)}},[toast]);
 function go(p:Page){keyboard.hide();setPage(p==='home'?'club':p);setSheet('');setQuery('')}
 function open(s:string){keyboard.hide();setSheet(s)}
 function editPlayer(i:number|null){setEdit(i);setName(i===null?'':players[i].name);setRating(i===null?'1000':String(players[i].rating));setRole(i===null?(page==='session'?'Guest':'Member'):players[i].role);open('player')}
 function savePlayer(){if(!name.trim()||!Number.isFinite(Number(rating))||Number(rating)<0||Number(rating)>5000){setToast('Enter a name and rating from 0 to 5000.');return}const p={name:name.trim(),rating:Math.round(Number(rating)),role};setPlayers(x=>edit===null?[...x,p]:x.map((v,i)=>i===edit?{...v,...p}:v));keyboard.hide();setSheet('');setToast(edit===null?'Player added':'Player updated')}
 function changeScore(c:number,i:number,v:string){setScores(x=>x.map((a,j)=>j===c?a.map((n,k)=>k===i?v:n):a))}
 const isSession=page==='session',paused=players.filter(p=>p.paused).length;
 const teams=nextStarted?[['Amir','Nadia'],['Rafi','Zul']]:[['Aiman','Siti'],['Farah','Haziq']];
 const mainNav=[{text:'Club',icon:UsersThree,dest:'club'},{text:'Sessions',icon:CalendarBlank,dest:'sessions'},{text:'Profile',icon:UserCircle,dest:'profile'}] as const;
 function Row({title,sub,icon:Icon=UsersThree,onClick}:{title:string;sub?:string;icon?:typeof UsersThree;onClick:()=>void}){return <button className="link-row" onClick={onClick}><Icon size={25} weight="duotone"/><span><strong>{title}</strong>{sub&&<small>{sub}</small>}</span><CaretRight size={18}/></button>}
 function Stats(){return <div className="stats-card"><div><small>Club rating</small><strong className="big-number">{config.rating}</strong><span className="gain"><ArrowUp size={14}/>{config.id==='anti'?'+19':config.id==='weekend'?'+12':'0'} <em>last session</em></span></div><div><small>Club rank</small><strong className="big-number">{config.rank?`#${config.rank}`:'—'}</strong><span className="gain"><ArrowUp size={14}/>{config.rank?1:0} <em>{config.rank?`from #${config.rank+1}`:'Not ranked'}</em></span></div></div>}
 function Recent(){return <button className="recent-card" onClick={()=>go('recap')}><CalendarBlank size={22}/><span><small>Recent session</small><strong>{config.recent}</strong><span className="result"><b>{config.wins} / {config.games}</b> wins</span></span><CaretRight size={18}/></button>}
 function Roster({manage=false}:{manage?:boolean}){const list=players.map((p,i)=>({p,i})).filter(({p})=>p.name.toLowerCase().includes(query.toLowerCase()));return <div className="roster">{list.map(({p,i})=><div className="person" key={i}><span className={'avatar tone'+i%5}>{p.name[0]}</span><span className="person-info"><strong>{p.name}</strong><small>{isSession?(p.paused?'Taking a break':'Available'):p.role} · {p.rating}</small></span>{isSession?<button className="icon-button" aria-label={`${p.paused?'Resume':'Pause'} ${p.name}`} onClick={()=>{setPlayers(x=>x.map((v,j)=>i===j?{...v,paused:!v.paused}:v));setToast(p.paused?`${p.name} is available`:`${p.name} is taking a break`)}}>{p.paused?<Play size={20}/>:<Pause size={20}/>}</button>:manage?<button className="icon-button" aria-label={'Edit '+p.name} onClick={()=>editPlayer(i)}><PencilSimple size={20}/></button>:<strong>{p.rating}</strong>}</div>)}{!list.length&&<p className="empty">No players found.</p>}</div>}
 return <div className="pc-app" onFocusCapture={keepFrameStill}>
 <header className="pc-header">{['club','sessions','profile'].includes(page)?<><button className="club-switcher" aria-label={'Switch club, current '+clubName} onClick={()=>{setSheet('');onSwitch()}}><small>YOUR CLUB</small><strong>{clubName}<CaretRight size={16}/></strong></button><button className="icon-button" aria-label="Account settings" onClick={()=>open('account')}><UserCircle size={26}/></button></>:<><button className="icon-button" aria-label="Back" onClick={()=>go('club')}><ArrowLeft size={23}/></button><div><strong>{isSession||page==='recap'?sessionName:page==='admin'?'Manage club':'New session'}</strong><small>{clubName}</small></div><button className="icon-button" aria-label="More options" onClick={()=>open('menu')}><DotsThree size={26}/></button></>}</header>
 {page==='admin'&&<div className="local-tabs" role="tablist">{['Players','Requests','Settings'].map(t=><button role="tab" aria-selected={adminTab===t} className={adminTab===t?'selected':''} onClick={()=>{keyboard.hide();setAdminTab(t)}} key={t}>{t}{t==='Requests'&&requests.length>0&&<span className="count">{requests.length}</span>}</button>)}</div>}
 <MobileScroll key={page+adminTab+tab} className={'pc-scroll '+(page==='admin'?'with-tabs':'')}><main className="pc-content">
 {page==='club'&&<><div className="club-welcome"><div><span className="eyebrow">{config.owner?'YOUR CLUB, TOGETHER':'GOOD TO SEE YOU'}</span><h1>{config.owner?'Ready for a rally?':'Welcome back, Aiman.'}</h1></div><img src="/spark.png" alt="Friendly spark"/></div>{config.owner&&!ended?<div className="session-tile"><span className="eyebrow">LIVE NOW</span><h2>{sessionName}</h2><p>{players.length} players · 2 courts</p><button className="primary" onClick={()=>{setTab('Courts');go('session')}}>Continue hosting<CaretRight size={19}/></button></div>:<div className="card"><h2>{config.games?'All caught up.':'Make your first session.'}</h2><p className="muted">{config.games?'No live session in this club.':'Add your players and get everyone playing.'}</p><button className="primary" onClick={()=>go(config.owner?'setup':'sessions')}>{config.owner?'Start a session':'Browse sessions'}</button></div>}<div className="link-group">{config.owner&&<Row title="Manage club" sub="Players, requests and settings" icon={GearSix} onClick={()=>{setAdminTab('Players');go('admin')}}/>}<Row title="Club standings" sub="Ratings in this club" icon={Trophy} onClick={()=>open('club-standings')}/></div><div className="section-heading"><h3>Your progress here</h3><button className="text-button" onClick={()=>go('profile')}>View profile</button></div><Stats/>{config.games>0&&<><h3>Recent activity</h3><Recent/></>}</>}
 {page==='sessions'&&<><div className="section-heading"><h1>Sessions</h1>{config.owner&&<button className="secondary" onClick={()=>go('setup')}><Plus size={18}/>New</button>}</div>{!ended&&<div className="session-tile"><span className="eyebrow">LIVE NOW</span><h2>{sessionName}</h2><p>{players.length} players · 2 courts</p><button className="primary" onClick={()=>{setTab('Courts');go('session')}}>Continue hosting</button></div>}<h3>Past sessions</h3>{config.games>0?<Recent/>:<div className="empty"><CalendarBlank size={32}/><h3>No sessions yet</h3><p>Your club's completed sessions will appear here.</p></div>}</>}
 {page==='profile'&&<><div className="profile-heading"><span className="avatar large tone0">A</span><h1>Aiman</h1><p>{clubName}</p></div><Stats/><div className="section-heading"><h3>Recent form</h3><small>Last {config.games} matches</small></div><div className="form-strip">{(config.id==='anti'?['W','W','L','W','L','W']:config.games?['W','L','W','L','W']:[]).map((r,i)=><span className={r==='W'?'win':'loss'} key={i}>{r}</span>)}</div>{config.games>0&&<Recent/>}<h3>Achievements</h3>{config.games===0?<p className="muted">Play your first session to start earning achievements.</p>:<button className="achievement" onClick={()=>open('achievement')}><Trophy size={32} weight="duotone"/><span><small>Achievement earned</small><strong>Strong Start</strong></span><CaretRight size={18}/></button>}<div className="link-group"><Row title="Account settings" sub="Your name and preferences" icon={GearSix} onClick={()=>open('account')}/></div><details><summary>How ratings work</summary><p>Club ratings reflect match results. Achievements are separate from the rating used to balance teams.</p></details></>}
 {page==='admin'&&<>{adminTab==='Players'?<><label className="search"><MagnifyingGlass size={20}/><KeyboardInput aria-label="Search players" placeholder="Search players by name" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}><X size={16}/></button>}</label><div className="button-pair"><button className="primary" onClick={()=>editPlayer(null)}><Plus size={20}/>Add player</button><button className="secondary" onClick={()=>open('invite')}><LinkSimple size={19}/>Invite link</button></div><Roster manage/></>:adminTab==='Requests'?<><h2>Requests</h2><p className="muted">Review who joins your club.</p>{requests.map(r=><div className="card" key={r}><strong>{r}</strong><div className="button-pair spaced"><button className="primary" onClick={()=>{setRequests(x=>x.filter(y=>y!==r));setToast('Request approved')}}>Approve</button><button className="secondary" onClick={()=>{setRequests(x=>x.filter(y=>y!==r));setToast('Request declined')}}>Decline</button></div></div>)}{!requests.length&&<div className="empty"><Check size={32}/><h3>All caught up</h3><p>No pending requests.</p></div>}</>:<><h2>Club settings</h2><label className="field-label">Club name<KeyboardInput value={clubName} onChange={e=>setClubName(e.target.value)}/></label><button role="switch" aria-checked={openClub} className="toggle-row" onClick={()=>setOpenClub(!openClub)}><span><strong>Allow join requests</strong><small>New players can request access</small></span><span className={'switch '+(openClub?'on':'')}/></button><button className="primary" disabled={!clubName.trim()} onClick={()=>{setToast('Club settings saved');keyboard.hide()}}>Save changes</button><details><summary>Advanced settings</summary><p>Connect profiles across clubs only when both clubs confirm they belong to the same person.</p><button className="secondary" onClick={()=>open('identity')}>Connect player profiles</button></details></>}</>}
 {isSession&&<>{ended?<div className="empty"><Check size={38}/><h2>Session finished</h2><p>Everyone has stopped playing.</p><button className="primary" onClick={()=>go('recap')}>View recap</button></div>:tab==='Courts'?<><div className="session-summary"><span><i className="live-indicator"/>Live session</span><small>{players.length} players · 2 courts</small></div>{[0,1].map(c=><section className="court-card" key={c}><div className="section-heading"><h3>Court {c+1}</h3><span className={'court-status '+(c?'green':'')}>{saved[c]?'Complete':'Playing now'}</span>{c===1&&!saved[c]&&<button className="court-edit" onClick={()=>{setCourt(1);open('court-score')}}>Enter score</button>}</div>{saved[c]?<><div className="saved-result"><strong>{scores[c][0]} <span>–</span> {scores[c][1]}</strong><span className="gain"><Check size={17}/>Result saved</span></div><button className="secondary full" onClick={()=>{setSaved(x=>x.map((v,i)=>i===c?false:v));setCourt(c);if(c===1)open('court-score')}}>Correct score</button></>:<>{(c===0?teams:[['Danish','Aina'],['Mira','Irfan']]).map((team,i)=><div className="team-row" key={i}><strong>{team[0]}<br/>{team[1]}</strong>{c===0?<><KeyboardInput type="number" min="0" max="99" aria-label={'Team '+(i+1)+' score'} value={scores[c][i]} onChange={e=>changeScore(c,i,e.target.value)}/><div className="steppers"><button aria-label={'Increase team '+(i+1)+' score'} onClick={()=>changeScore(c,i,String(Math.min(99,Number(scores[c][i])+1)))}><Plus size={16}/></button><button aria-label={'Decrease team '+(i+1)+' score'} onClick={()=>changeScore(c,i,String(Math.max(0,Number(scores[c][i])-1)))}><Minus size={16}/></button></div></>:<span className="score-placeholder">{scores[c][i]==='0'?'–':scores[c][i]}</span>}</div>)}{c===0&&<button className="primary" onClick={()=>{setCourt(c);open('score')}}>Save score</button>}</>}</section>)}<button className="next-up" onClick={()=>open('next')}><Clock size={21}/><span><strong>Next up</strong><small>Amir · Nadia · Rafi · Zul</small></span><CaretRight size={18}/></button></>:tab==='Players'?<><div className="section-heading"><h2>Players</h2><small>{paused} taking a break</small></div><button className="primary" onClick={()=>editPlayer(null)}><Plus/>Add guest</button><Roster/></>:<><div className="section-heading"><h2>Standings</h2><span className="pill">Session</span></div><p className="muted">Leading this session</p><div className="roster">{['Aiman','Siti','Farah','Haziq','Danish','Aina'].map((n,i)=><div className="person" key={n}><span className={'rank '+(i===0?'first':'')}>{i+1}</span><strong className="person-info">{n}</strong><span><b>{[84,80,76,72,69,65][i]}</b><small> points</small></span></div>)}</div><details><summary>How rankings work</summary><p>Sample standings for this preview. The live app's ranking rules will be preserved.</p></details></>}</>}
 {page==='recap'&&<><div className="celebration"><img src="/medallion.png" alt="Celebrating your session"/><h1>Session complete!</h1><p>Great games today, Aiman.</p></div><div className="stats-card recap-stats"><div><small>Rating</small><strong>{config.rating-(config.id==='anti'?19:12)} → {config.rating}</strong><span className="gain">+{config.id==='anti'?19:12}</span></div><div><small>Session result</small><strong>{config.wins} / {config.games}</strong><small>wins</small></div></div><button className="achievement" onClick={()=>open('achievement')}><Trophy size={34} weight="duotone"/><span><small>Achievement earned</small><strong>Strong Start</strong></span><CaretRight size={19}/></button><button className="primary" onClick={()=>go('profile')}>View progress</button><button className="text-button" onClick={()=>go('club')}>Back to club</button><p className="prototype-note">Sample recap · ratings are illustrative</p></>}
 {page==='setup'&&<><h1>Get everyone playing.</h1><p className="muted">A few details, then you're ready.</p><label className="field-label">Session name<KeyboardInput value={sessionName} onChange={e=>setSessionName(e.target.value)}/></label><div className="setting-line"><span>Courts</span><strong>2</strong></div><div className="setting-line"><span>Matchmaking</span><strong>Balanced</strong></div><div className="setting-line"><span>Players</span><strong>{players.length} selected</strong></div><button className="secondary full" onClick={()=>{setAdminTab('Players');go('admin')}}>Manage roster</button><button className="primary" disabled={!sessionName.trim()||players.length<4} onClick={()=>{setEnded(false);setSaved([false,false]);setNextStarted(false);setScores([['0','0'],['0','0']]);setTab('Courts');go('session');setToast('Session started')}}>Start session</button><p className="prototype-note">Sample setup · 2 courts and Balanced format</p></>}
 </main></MobileScroll>
 {page!=='recap'&&page!=='setup'&&!keyboardHeight&&<nav className="bottom-nav" aria-label={isSession?'Session navigation':'Main navigation'}>{isSession?['Courts','Players','Standings'].map((t,i)=>{const Icon=[House,UsersThree,ChartBar][i];return <button key={t} aria-current={tab===t?'page':undefined} className={tab===t?'active':''} onClick={()=>{keyboard.hide();setTab(t)}}><Icon size={25} weight={tab===t?'fill':'regular'}/><span>{t}</span></button>}):mainNav.map(({text,icon:Icon,dest})=>{const active=page===dest||(dest==='club'&&page==='admin');return <button key={text} aria-current={active?'page':undefined} className={active?'active':''} onClick={()=>go(dest)}><Icon size={25} weight={active?'fill':'regular'}/><span>{text}</span></button>})}</nav>}
 {toast&&<div className="toast" role="status" style={{bottom:Math.max(bottomInset+16,96)}}><Check size={19}/>{toast}</div>}
 <BottomSheet open={!!sheet} onOpenChange={v=>{if(!v)setSheet('')}} title={sheet==='player'?(edit===null?'Add player':'Edit '+players[edit]?.name):sheet==='score'?'Confirm result':sheet==='menu'?'Options':sheet==='end'?'End this session?':sheet==='invite'?'Invite to your club':sheet==='next'?'Next match':sheet==='court-score'?'Court 2 score':sheet==='achievement'?'Strong Start':sheet==='create-club'?'Create a club':sheet==='join-club'?'Join a club':sheet==='remove'?'Remove player?':sheet==='account'?'Your account':sheet==='club-standings'?'Club standings':'Connect profiles'}><div className="sheet-content" onFocusCapture={keepFrameStill}>
 {sheet==='player'&&<><label className="field-label">Name<KeyboardInput placeholder="Player name" value={name} onChange={e=>setName(e.target.value)}/></label><label className="field-label">Rating<KeyboardInput type="number" value={rating} onChange={e=>setRating(e.target.value)}/></label>{!isSession&&<label className="field-label">Membership<select value={role} onChange={e=>setRole(e.target.value)}>{['Member','Occasional','No account','Owner'].map(r=><option key={r}>{r}</option>)}</select></label>}<button className="primary" onClick={savePlayer}>{edit===null?'Add player':'Save changes'}</button>{edit!==null&&<button className="danger text-button" onClick={()=>open('remove')}>Remove player</button>}</>}
 {sheet==='remove'&&<><p>Remove {edit===null?'this player':players[edit]?.name} from this sample roster?</p><button className="primary" onClick={()=>{setPlayers(x=>x.filter((_,i)=>i!==edit));setSheet('');setToast('Player removed')}}>Remove player</button><button className="text-button" onClick={()=>open('player')}>Keep player</button></>}
 {sheet==='menu'&&<>{isSession?<><Row title="Session settings" sub="Balanced · 2 courts" icon={GearSix} onClick={()=>{setSheet('');setToast('Sample session uses Balanced format and 2 courts')}}/><Row title="End session" icon={SignOut} onClick={()=>open('end')}/></>:<><Row title="Go to club" onClick={()=>go('club')}/>{config.owner&&<Row title="Manage club" icon={GearSix} onClick={()=>go('admin')}/>}</>}<button className="text-button" onClick={()=>{setPlayers(config.id==='anti'?initial:[{name:'Aiman',rating:config.rating,role:config.owner?'Owner':'Member'}]);setEnded(config.id!=='anti');setSaved([false,false]);setScores([['18','16'],['0','0']]);setNextStarted(false);setSessionName(config.recent);setRequests(['Nadia wants to connect her account','Rafi wants to join the club']);go('club');setToast('Sample session reset')}}>Reset demo</button></>}
 {sheet==='score'&&<><p>Court {court+1}</p><div className="confirmation-score">{scores[court][0]} <span>–</span> {scores[court][1]}</div><p className="muted">Check both scores before saving.</p><button className="primary" onClick={()=>{if(scores[court].some(v=>v===''||!Number.isInteger(Number(v))||Number(v)<0||Number(v)>99)){setToast('Enter whole scores from 0 to 99');return}setSaved(x=>x.map((v,i)=>i===court?true:v));setSheet('');setToast('Result saved')}}>Confirm result</button><button className="text-button" onClick={()=>setSheet('')}>Keep editing</button></>}
 {sheet==='court-score'&&<><label className="field-label">Danish & Aina<KeyboardInput type="number" value={scores[1][0]} onChange={e=>changeScore(1,0,e.target.value)}/></label><label className="field-label">Mira & Irfan<KeyboardInput type="number" value={scores[1][1]} onChange={e=>changeScore(1,1,e.target.value)}/></label><button className="primary" onClick={()=>open('score')}>Review result</button></>}
 {sheet==='end'&&<><p>Finish {sessionName} and view the recap? Everyone will stop playing.</p>{saved.some(v=>!v)&&<p className="muted">There are unsaved court results. Save them first if you want to keep them.</p>}<button className="primary" onClick={()=>{setEnded(true);setPlayers(x=>x.map(p=>({...p,paused:false})));go('recap')}}>End session</button><button className="text-button" onClick={()=>setSheet('')}>Keep playing</button></>}
 {sheet==='next'&&<><div className="next-teams"><strong>Amir & Nadia</strong><span>vs</span><strong>Rafi & Zul</strong></div><p className="muted">Court 1{saved[0]?' is ready.':' is still in use.'}</p><button className="primary" disabled={!saved[0]} onClick={()=>{setNextStarted(true);setSaved(x=>[false,x[1]]);setScores(x=>[['0','0'],x[1]]);setSheet('');setToast('Next match started on Court 1')}}>Start next match</button></>}
 {sheet==='invite'&&<><p>Share access to {clubName}.</p><div className="sample-link">anti-selek.app/invite/sample-club</div><button className="primary" onClick={async()=>{try{await navigator.clipboard.writeText('https://anti-selek.app/invite/sample-club');setToast('Sample invite link copied')}catch{setToast('Copy the sample link shown above')}}}><LinkSimple size={19}/>Copy sample link</button><p className="prototype-note">Preview link only — no invitation is sent.</p></>}
 {sheet==='achievement'&&<><img className="achievement-art" src="/spark.png" alt="Happy spark"/><h2>A strong start.</h2><p>You earned this achievement in {config.recent}.</p><button className="primary" onClick={()=>setSheet('')}>Nice!</button></>}
 {(sheet==='create-club'||sheet==='join-club')&&<><label className="field-label">{sheet==='create-club'?'Club name':'Invite link'}<KeyboardInput value={draft} placeholder={sheet==='create-club'?'Your club name':'Paste an invite link'} onChange={e=>setDraft(e.target.value)}/></label><button className="primary" disabled={!draft.trim()} onClick={()=>{if(sheet==='create-club')setExtraClubs(x=>[...x,draft.trim()]);keyboard.hide();setSheet('');setToast(sheet==='create-club'?'Sample club created':'Sample join request sent')}}>{sheet==='create-club'?'Create club':'Request to join'}</button></>}
 {sheet==='identity'&&<><p>Find a player without an account to connect their profile across clubs.</p><button className="primary" onClick={()=>{setAdminTab('Players');setQuery('Amir');setSheet('')}}>Find player</button></>}
 {sheet==='account'&&<><p>Aiman · Sample account</p><p className="muted">Account details are read-only in this prototype.</p><button className="primary" onClick={()=>setSheet('')}>Done</button></>}
 {sheet==='club-standings'&&<div className="roster">{players.slice().sort((a,b)=>b.rating-a.rating).map((p,i)=><div className="person" key={p.name}><span className="rank">{i+1}</span><strong className="person-info">{p.name}</strong><strong>{p.rating}</strong></div>)}</div>}
 </div></BottomSheet></div>
}
