ALTER TABLE "Session" ADD COLUMN "poolsEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Session" ADD COLUMN "poolAName" TEXT;
ALTER TABLE "Session" ADD COLUMN "poolBName" TEXT;
ALTER TABLE "Session" ADD COLUMN "poolACourtAssignments" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Session" ADD COLUMN "poolBCourtAssignments" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Session" ADD COLUMN "poolAMissedTurns" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Session" ADD COLUMN "poolBMissedTurns" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Session" ADD COLUMN "crossoverMissThreshold" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "SessionPlayer" ADD COLUMN "pool" TEXT NOT NULL DEFAULT 'A';
ALTER TABLE "QueuedMatch" ADD COLUMN "targetPool" TEXT;
