// @vitest-environment jsdom
import {act} from 'react';
import {createRoot, type Root} from 'react-dom/client';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
const mocks=vi.hoisted(()=>({status:'authenticated',replace:vi.fn()}));
vi.mock('next-auth/react',()=>({useSession:()=>({status:mocks.status,data:{user:{id:'me',name:'Real Player'}}}),signOut:vi.fn()}));
vi.mock('next/navigation',()=>({useRouter:()=>({replace:mocks.replace})}));
vi.mock('@phosphor-icons/react',async(importOriginal)=>{const actual=await importOriginal<typeof import('@phosphor-icons/react')>();return{...actual,...Object.fromEntries(['UsersThree','UserCircle','CalendarBlank','CaretRight','ArrowLeft','ArrowUp','GearSix','Trophy','Scales','Plus','MagnifyingGlass','LinkSimple','PencilSimple','Check','DotsThree','House','ChartBar','Minus','Pause','Play','Clock','SignOut','X'].map(name=>[name,()=>null]))}});
vi.mock('next/image',()=>({default:()=>null}));
import Page from './page';
let container:HTMLDivElement;let root:Root;
const club={id:'club',name:'Real Club',role:'ADMIN',viewerIsOwner:true,membersCount:4};
const historySession={id:'session-1',code:'history-1',name:'Admission History Session',date:'2026-10-04T00:00:00.000Z',matches:1,wins:1,losses:0,winRate:1,pointDifferential:6,ratingChange:5,ratingVerified:true};
const historyMatch={id:'match-1',date:'2026-10-04T00:00:00.000Z',sessionId:'session-1',sessionCode:'history-1',sessionName:'Admission History Session',partner:{id:'partner-1',name:'Partner'},opponents:[{id:'opponent-1',name:'Opponent One'},{id:'opponent-2',name:'Opponent Two'}],score:'21-15',result:'WIN',eloChange:5,pointDifferential:6};
const memberProfile={latestSession:historySession,recentForm:[historyMatch],timeline:[{id:'entry-1',kind:'SESSION',date:historySession.date,rating:1234,delta:5,sessionId:historySession.id,label:historySession.name,session:historySession}],records:{highestRating:{value:1234,date:historySession.date},longestStreak:null,bestSession:historySession},history:{items:[historySession],hasMore:false,nextOffset:null},matchHistory:[historyMatch],relationships:{partners:[],rivals:[],partner:null,rival:null}};
const fetcher=vi.fn(async(url:string)=>({ok:true,json:async()=>url==='/api/clubs'?[club]:url==='/api/user/me'?{user:{id:'account-me',name:'Real Player',email:'real@example.com',gender:'MALE',avatarUrl:null,isQuickAccess:false},players:[{id:'player-me',name:'Real Player',gender:'FEMALE',avatarUrl:null}]}:url==='/api/clubs/club/achievements'?{achievements:[],showcase:[],unseen:[]}:url.startsWith('/api/users/')?{user:{id:'player-me',name:'Real Player',elo:1234,avatarUrl:null},profile:memberProfile,achievements:[{title:'Backend achievement must not render'}]}:{club,viewer:{id:'account-me',userId:'account-me',playerId:'player-me',name:'Real Player'},clubMembers:[{id:'player-me',name:'Real Player',ownerUserId:'account-me',elo:1234}],sessions:[],claimRequests:[]}}));
beforeEach(()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true,matchMedia:vi.fn(()=>({matches:false,media:'',onchange:null,addListener:vi.fn(),removeListener:vi.fn(),addEventListener:vi.fn(),removeEventListener:vi.fn(),dispatchEvent:vi.fn()}))});vi.stubGlobal('ResizeObserver',class{observe(){}unobserve(){}disconnect(){}});Element.prototype.scrollTo=vi.fn();mocks.status='authenticated';localStorage.clear();vi.stubGlobal('fetch',fetcher);container=document.createElement('div');document.body.append(container);root=createRoot(container)});
afterEach(async()=>{await act(async()=>root.unmount());container.remove();vi.unstubAllGlobals();vi.clearAllMocks()});
async function render(){await act(async()=>{root.render(<Page/>);await new Promise(r=>setTimeout(r,20))});}
async function click(label:string){const button=Array.from(container.querySelectorAll('button')).find(b=>b.textContent===label);expect(button).toBeTruthy();await act(async()=>{button!.click();await new Promise(r=>setTimeout(r,20))})}
it('loads the real club in a native browser shell without a device simulator',async()=>{await render();expect(container.textContent).toContain('Real Club');expect(container.querySelector('.prototype-root')).toBeTruthy();expect(container.textContent).not.toContain('iPhone');expect(container.querySelectorAll('nav button')).toHaveLength(4)});
it('uses Player profile results and club achievements without rendering legacy account stats',async()=>{await render();await click('Profile');expect(container.textContent).toContain('1234');expect(container.textContent).toContain('1 sessions · 1 matches');expect(container.textContent).toContain('Admission History Session');expect(container.textContent).toContain('0 badges unlocked');expect(container.textContent).not.toContain('Backend achievement must not render')});
it('redirects unauthenticated visitors to sign-in',async()=>{mocks.status='unauthenticated';await render();expect(mocks.replace).toHaveBeenCalledWith('/signin?callbackUrl=%2F')});
