import {beforeAll,afterAll,beforeEach,it,expect,vi} from 'vitest';
import {PrismaClient} from '@prisma/client';
import {execFileSync} from 'node:child_process';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
let db:PrismaClient;let actor:{id:string;isAdmin?:boolean;isQuickAccess?:boolean}|null={id:'owner'};
vi.mock('@/lib/prisma',()=>({get prisma(){return db}}));
vi.mock('@/lib/auth',()=>({auth:async()=>actor?{user:actor}:null}));
vi.mock('@/lib/rateLimit',()=>({rateLimit:async()=>null}));
import {POST} from './route';
import {GET,PATCH as settings} from '../[id]/join-requests/route';
import {PATCH as review} from '../[id]/join-requests/[requestId]/route';
const dir=mkdtempSync(path.join(tmpdir(),'prototype-join-'));const file=path.join(dir,'test.db');
const context={params:Promise.resolve({id:'club'})};
const request=(body:unknown)=>new Request('http://localhost/api/clubs/join-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
beforeAll(async()=>{writeFileSync(file,'');const url='file:'+file.replaceAll('\\','/');execFileSync(process.execPath,['node_modules/prisma/build/index.js','migrate','deploy'],{env:{...process.env,DATABASE_URL:url},stdio:'pipe'});db=new PrismaClient({datasources:{db:{url}}});},30000);
beforeEach(async()=>{await db.clubJoinRequest.deleteMany();await db.clubMember.deleteMany();await db.club.deleteMany();await db.user.deleteMany();await db.user.createMany({data:[{id:'owner',name:'Owner'},{id:'member',name:'Member'},{id:'outsider',name:'Outsider'}]});await db.club.create({data:{id:'club',name:'Club',createdById:'owner',allowJoinRequests:true}});actor={id:'owner'};});
afterAll(async()=>{await db?.$disconnect();rmSync(dir,{recursive:true,force:true});});
it('requires an account and blocks quick access',async()=>{actor=null;expect((await POST(request({clubId:'club'}))).status).toBe(401);actor={id:'member',isQuickAccess:true};expect((await POST(request({clubId:'club'}))).status).toBe(403);});
it('deduplicates pending requests and adds membership only on approval',async()=>{actor={id:'member'};const first=await(await POST(request({clubId:'club'}))).json();await POST(request({clubId:'club'}));expect(await db.clubJoinRequest.count()).toBe(1);expect(await db.clubMember.count()).toBe(0);actor={id:'owner'};const ctx={params:Promise.resolve({id:'club',requestId:first.id})};expect((await review(request({action:'APPROVE'}),ctx)).status).toBe(200);expect(await db.clubMember.findUnique({where:{clubId_userId:{clubId:'club',userId:'member'}}})).toMatchObject({role:'MEMBER'});expect((await review(request({action:'APPROVE'}),ctx)).status).toBe(409);expect(await db.clubMember.count()).toBe(1);});
it('rejects requests without granting membership and permits explicit resubmission',async()=>{actor={id:'member'};const entry=await(await POST(request({clubId:'club'}))).json();actor={id:'owner'};await review(request({action:'REJECT'}),{params:Promise.resolve({id:'club',requestId:entry.id})});expect(await db.clubMember.count()).toBe(0);actor={id:'member'};await POST(request({clubId:'club'}));expect(await db.clubJoinRequest.count({where:{status:'PENDING'}})).toBe(1);});
it('enforces admin access and the join-request switch',async()=>{actor={id:'outsider'};expect((await GET(request({}),context)).status).toBe(403);expect((await settings(request({allowJoinRequests:false}),context)).status).toBe(403);actor={id:'owner'};expect((await settings(request({allowJoinRequests:false}),context)).status).toBe(200);actor={id:'member'};expect((await POST(request({clubId:'club'}))).status).toBe(403);expect(await db.clubJoinRequest.count()).toBe(0);});
it('cannot review a request through another club',async()=>{actor={id:'member'};const entry=await(await POST(request({clubId:'club'}))).json();actor={id:'owner'};await db.club.create({data:{id:'other',name:'Other',createdById:'owner'}});expect((await review(request({action:'APPROVE'}),{params:Promise.resolve({id:'other',requestId:entry.id})})).status).toBe(404);expect(await db.clubMember.count()).toBe(0);});
